<?php
/*
 ****************************
 * YTP-Drupal-tools plugin inserts content from ckan to the rupal instance on 
 * avoindata.fi service
 ****************************
 */
function ytp_user_user_login(&$edit, $account) {

	debug($account);
	$namevar = $account -> name;
	debug($namevar);
	$ckan_user_json = file_get_contents("http://localhost/data/api/3/action/user_show?id=" . $namevar);
	debug($ckan_user_json);
	$php_user = json_decode($ckan_user_json);
	debug($php_user);
	global $user;
	debug($user);
	$user->fullname=$php_user->fullname;
	debug($user);

	
}
function ytp_user_page_build(&$page){
	debug(services_endpoint_new()  );
}


function ytp_user_enable() {
  // Check if our field is not already created.
  if (!field_info_field('field_fullname')) {
    $field = array(
        'field_name' => 'field_fullname', 
        'type' => 'text', 
        'cardinality' => 1,
    	'translatable' => FALSE, 
    );
    field_create_field($field);

    // Create the instance on the bundle.
    $instance = array(
        'field_name' => 'field_fullname', 
        'entity_type' => 'user', 
        'label' => 'Fullname', 
        'bundle' => 'user', 
        // If you don't set the "required" property then the field wont be required by default.
        'required' => TRUE,
        'settings' => array(
           // Here you inform either or not you want this field showing up on the registration form.
            'user_register_form' => 1,
        ),
        'widget' => array(
            'type' => 'textfield',
            'weight' => '1',
        ), 
    );
    field_create_instance($instance);
	drupal_set_message($field['field_fullname'].' was created.');
  }
}