<?php

/**
 * @file
 * Adds avoindata footer.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_footer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_footer':
      return t('
        Creates footer module.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_footer_theme($existing, $type, $theme, $path) {
  return [
    'avoindata_footer' => [
      'template' => 'avoindata_footer_block',
      'variables' => [],
    ],
  ];
}
