version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: pip
  directory: "/ckan/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/ckan/"
  schedule:
    interval: daily
    time: "03:00"
- package-ecosystem: "docker"
  directory: "/drupal/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/docker/solr/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/docker/nginx/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/docker/postgres/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: "docker"
  directory: "/docker/datapusher-plus/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/opendata-assets/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  registries:
  - npm-registry-npm-fontawesome-com

- package-ecosystem: npm
  directory: "/drupal/modules/avoindata-header/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/drupal/modules/avoindata-articles/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10

- package-ecosystem: "composer"
  directory: "/drupal/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/cdk/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10


- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
