extend-exclude = [
  "ckanext-spatial",
  "ckanext-prh_tools",
  "ckanext-dcat",
  "ckanext-fluent",
  "ckanext-sitesearch",
  "ckanext-scheming",
  "ckanext-ytp_comments"
]

line-length = 127

[lint]
select = ["E", "F"]
