<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_infobox_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_infobox':
      return t('
        Creates infobox module.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_infobox_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_infobox' => array(
      'template' => 'avoindata_infobox_block',
    ),
  );
}
