---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloudfront CDN for Opendata'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label: 'Cloudfront parameters'
      Parameters:
      - Aliases
      - Compress
      - DefaultTTL
      - MinTTL
      - MaxTTL
      - LogIncludeCookies
      - LogEnabled
      - OriginKeepaliveTimeout
      - OriginReadTimeout
      - OriginSSLProtocols
      - OriginDomainName
    - Label: 'Route 53 parameters'
      Parameters:
      - HostedZoneId
      - HostedZoneIdAlternate
Parameters:
  EnvironmentName:
    Description: Name of the environment (infratest, dev, alpha, beta, prod)
    Type: 'AWS::SSM::Parameter::Value<String>'
  DNSHostName:
    Description: Host name for DNS record (e.g. infratest, dev, www)
    Type: 'AWS::SSM::Parameter::Value<String>'
  Aliases:
    Description: 'CNAME aliases for distribution'
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
  Compress:
    Description: 'Compress files that Cloudfront serves'
    Type: 'AWS::SSM::Parameter::Value<String>'
    # AllowedValues:
    #   - 'true'
    #   - 'false'
  DefaultTTL:
    Description: 'Default TTL for cache objects'
    Type: 'AWS::SSM::Parameter::Value<String>'
  MinTTL:
    Description: 'Minimum TTL for cache objects'
    Type: 'AWS::SSM::Parameter::Value<String>'
  MaxTTL:
    Description: 'Maximum TTL for cache objects'
    Type: 'AWS::SSM::Parameter::Value<String>'
  LogIncludeCookies:
    Description: 'Include cookies in CF access logs'
    Type: 'AWS::SSM::Parameter::Value<String>'
    # AllowedValues:
      # - 'true'
      # - 'false'
  LogEnabled:
    Description: 'Enable CF access logging'
    Type: 'AWS::SSM::Parameter::Value<String>'
  LogExpirationDays:
    Description: 'Days before removing Cloudfront logs'
    Type: 'AWS::SSM::Parameter::Value<String>'
  OriginKeepaliveTimeout:
    Description: 'Origin keepalive time for connections in seconds'
    Type: 'AWS::SSM::Parameter::Value<String>'
  OriginReadTimeout:
    Description: 'Origin response timeout in seconds'
    Type: 'AWS::SSM::Parameter::Value<String>'
  OriginSSLProtocols:
    Description: 'List of SSL/TLS protocols CF can use for origin'
    Type: 'AWS::SSM::Parameter::Value<List<String>>'
  AcmCertificateArn:
    Description: 'ARN of the certificate in ACM to use'
    Type: 'AWS::SSM::Parameter::Value<String>'
  OriginDomainName:
    Description: 'DNS name of origin'
    Type: 'AWS::SSM::Parameter::Value<String>'
  HostedZoneId:
    Description: Zone ID for the DNS record
    Type: 'AWS::SSM::Parameter::Value<AWS::Route53::HostedZone::Id>'
  HostedZoneIdAlternate:
    Description: "[Optional] Zone ID for the DNS record"
    Type: 'AWS::SSM::Parameter::Value<String>'
  DNSDomainName:
    Description: "Domain name"
    Type: 'AWS::SSM::Parameter::Value<String>'
  AlternateDNSDomainName:
    Description: "Alternate Domain name"
    Type: 'AWS::SSM::Parameter::Value<String>'
  WAFWebACLId:
    Description: "[Optional] Arn of WAF Web ACL"
    Type: String
Conditions:
  CreateAlternateDomainRecord: !Not [!Equals [!Ref HostedZoneIdAlternate, ""]]
  CloudfrontLogging: !Equals [!Ref LogEnabled, "true"]

Resources:
  Cloudfront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases: !Ref Aliases
        DefaultCacheBehavior:
          AllowedMethods:
          - "DELETE"
          - "GET"
          - "HEAD"
          - "OPTIONS"
          - "PATCH"
          - "POST"
          - "PUT"
          CachedMethods:
          - "GET"
          - "HEAD"
          - "OPTIONS"
          Compress: !Ref Compress
          MinTTL: !Ref MinTTL
          MaxTTL: !Ref MaxTTL
          DefaultTTL: !Ref DefaultTTL
          ForwardedValues:
            Cookies:
              Forward: 'whitelist'
              WhitelistedNames:
              - 'SESS*'
              - 'SSESS*'
              - 'ckan'
            Headers:
            - 'CloudFront-Forwarded-Proto'
            - 'Host'
            - 'Origin'
            - 'Accept'
            QueryString: true
          TargetOriginId: OpendataOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        Logging: !If
          - CloudfrontLogging
          - Bucket: !GetAtt LogBucket.DomainName
            IncludeCookies: !Ref LogIncludeCookies
            Prefix: !Ref EnvironmentName
          - !Ref "AWS::NoValue"
        Origins:
          - Id: OpendataOrigin
            CustomOriginConfig:
              HTTPSPort: 443
              OriginKeepaliveTimeout: !Ref OriginKeepaliveTimeout
              OriginProtocolPolicy: 'https-only'
              OriginReadTimeout: !Ref OriginReadTimeout
              OriginSSLProtocols: !Ref OriginSSLProtocols
            DomainName: !Ref OriginDomainName
        PriceClass: 'PriceClass_100'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: 'TLSv1.1_2016'
          SslSupportMethod: 'sni-only'
        DefaultRootObject: 'fi'
        WebACLId: !Ref WAFWebACLId
      Tags:
        - Key: Name
          Value: !Sub avoindata-${EnvironmentName}

  DomainName:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${DNSHostName}.${DNSDomainName}.
      Type: A
      HostedZoneId: !Ref HostedZoneId
      AliasTarget:
        DNSName: !GetAtt Cloudfront.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2'

  DomainNameAlternate:
    Type: AWS::Route53::RecordSet
    Condition: CreateAlternateDomainRecord
    Properties:
      Name: !Sub ${DNSHostName}.${AlternateDNSDomainName}.
      Type: A
      HostedZoneId: !Ref HostedZoneIdAlternate
      AliasTarget:
        DNSName: !GetAtt Cloudfront.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2'

  LogBucket:
    Type: AWS::S3::Bucket
    Condition: CloudfrontLogging
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub avoindata-${EnvironmentName}-cloudfront-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref LogExpirationDays
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Stack:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
    Export:
      Name: !Sub ${AWS::StackName}
