---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates OIDC provider and IAM role for GitHub actions workflows.

#
# https://github.com/aws-actions/configure-aws-credentials#assuming-a-role
#

Parameters:
  GitHubOrgName:
    Description: Name for the GitHub organization.
    Type: String
  GitHubRepositoryName:
    Description: Name for the GitHub repository.
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String
  ECRRepositoryArn:
    Description: Arn for the ECR repositories.
    Type: String
  CreateBuildRole:
    Description: Is the build role required for this aws account
    Type: String
    Default: false
    AllowedValues: [true, false]
  CreateScanRole:
    Description: Is the scan role required for this aws account
    Type: String
    Default: false
    AllowedValues: [ true, false ]
  ToolsRepositoryArn:
    Description:  Arn for tools repository (Optional)
    Type: String

Conditions:
  CreateOIDCProvider: !Equals 
    - !Ref OIDCProviderArn
    - ""
  ShouldCreateBuildRole: !Equals ['true', !Ref CreateBuildRole]
  ShouldCreateScanRole: !Equals [ 'true', !Ref CreateScanRole ]

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      Description: Role for GitHub actions workflow.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If 
                - CreateOIDCProvider
                - !Ref GitHubOIDC
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrgName}/${GitHubRepositoryName}:*
      Policies:
        - PolicyName: ecr-login
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecr:GetAuthorizationToken"
                Resource: "*"

        - PolicyName: ecs-update-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecs:UpdateService"
                Resource: "*"

        - PolicyName: ecr-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                Resource: "*"

        - PolicyName: cfn-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "cloudformation:*"
                Resource: "*"

        - PolicyName: s3-cdk-bucket-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "arn:aws:s3:::cdktoolkit-stagingbucket-*"

        - PolicyName: sts-cdk-assume-permission
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sts:AssumeRole"
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/cdk-*"

        # NOTE: this is not needed since AWS CDK v2 bootstrap improvements!
        # - PolicyName: cfn-service-access
        #   PolicyDocument:
        #     Version: "2012-10-17"
        #     Statement:
        #       - Effect: Allow
        #         Action: "*"
        #         Resource: "*"
        #         Condition:
        #           ForAnyValue:StringEquals:
        #             aws:CalledVia: cloudformation.amazonaws.com

  BuildRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateBuildRole
    Properties:
      Description: Role for GitHub actions build workflow.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GitHubOIDC
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrgName}/${GitHubRepositoryName}:*
      Policies:
        - PolicyName: ecr-login
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecr:GetAuthorizationToken"
                Resource: "*"
        - PolicyName: ecr-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecr:*"
                Resource: !Ref ECRRepositoryArn

  ScanRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateScanRole
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GitHubOIDC
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrgName}/${GitHubRepositoryName}:*
      Policies:
        - PolicyName: ecr-tools-login
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecr:GetAuthorizationToken"
                Resource: "*"
        - PolicyName: ecr-tools-pull
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                Resource: !Ref ToolsRepositoryArn

  GitHubOIDC:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

Outputs:
  Role:
    Value: !GetAtt Role.Arn
  BuildRole:
    Condition: ShouldCreateBuildRole
    Value: !GetAtt BuildRole.Arn
