AWSTemplateFormatVersion: "2010-09-09"
Description: opendata application infrastructure

Parameters:
  EnvironmentName:
    Description: Name of the environment (infratest, dev, alpha, beta, www, prod)
    Type: 'AWS::SSM::Parameter::Value<String>'
  DatabaseSecurityGroup:
    Description: Security group of the RDS database
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>'
  EFSFileSystem:
    Description: Name of the EFS filesystem
    Type: 'AWS::SSM::Parameter::Value<String>'
  EFSSecurityGroup:
    Description: Security group of the EFS filesystem
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>'
  HostedZoneId:
    Description: Zone ID for the DNS record
    Type: 'AWS::SSM::Parameter::Value<AWS::Route53::HostedZone::Id>'
  HostedZoneIdAlternate:
    Description: "[Optional] Zone ID for the DNS record"
    Type: 'AWS::SSM::Parameter::Value<String>'
  NumberOfSubnets:
    Description: Number of subnets. This must match your selections in the list of load balancer subnets below.
    Type: 'AWS::SSM::Parameter::Value<String>'
  PublicALBSubnets:
    Description: The subnets to attach to the load balancer
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
  PrivateALBSubnets:
    Description: The subnets to attach to the load balancer
    Type: AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>
  PublicALBCertificate:
    Description: 'The AWS Certification Manager certificate ARN for the ALB certificate'
    Type: 'AWS::SSM::Parameter::Value<String>'
  RedisNodeType:
    Description: 'Node type for Elasticache Redis cluster nodes'
    Type: 'AWS::SSM::Parameter::Value<String>'
  RedisVersion:
    Description: 'Version of Redis to run'
    Type: 'AWS::SSM::Parameter::Value<String>'
  RedisMaintenanceWindow:
    Description: 'Maintenance window for Redis'
    Type: 'AWS::SSM::Parameter::Value<String>'
  Vpc:
    Description: Select an existing Vpc
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>'
  LogEnabled:
    Description: 'Enable ELB access logging'
    Type: 'AWS::SSM::Parameter::Value<String>'
  LogExpirationDays:
    Description: 'Days before removing ELB logs'
    Type: 'AWS::SSM::Parameter::Value<String>'
  WafHighPriorityRateLimit:
    Description: 'Max requests from high priority countries per 5 minute period for IP based rate limit rule'
    Type: 'AWS::SSM::Parameter::Value<String>'
  WafHighPriorityCountryCodes:
    Description: 'Country codes for locations, from where request limits are higher'
    Type: 'AWS::SSM::Parameter::Value<CommaDelimitedList>'
  WafHighPriorityRequestSampling:
    Description: 'Sample requests from high priority countries for viewing them in WAF console'
    Type: 'AWS::SSM::Parameter::Value<String>'
  WafRateLimit:
    Description: 'Max requests from rest of the world per 5 minute period for IP based rate limit rule'
    Type: 'AWS::SSM::Parameter::Value<String>'
  WafRequestSampling:
    Description: 'Sample requests from countries not in high priority list for viewing them in WAF console'
    Type: 'AWS::SSM::Parameter::Value<String>'
  WafAllTrafficRequestSampling:
    Description: 'Sample all requests for viewing them in WAF console'
    Type: 'AWS::SSM::Parameter::Value<String>'
  BannedIPs:
    Description: 'List of IP addresses to block (CIDR notation)'
    Type: 'AWS::SSM::Parameter::Value<CommaDelimitedList>'
  WafBannedIpsRequestSampling:
    Description: 'Sample requests from bad IPs for viewing them in WAF console'
    Type: 'AWS::SSM::Parameter::Value<String>'
  AllowedIPs:
    Description: 'List of IP addresses to allow (CIDR notation)'
    Type: 'AWS::SSM::Parameter::Value<CommaDelimitedList>'
  WafAllowedIpsRequestSampling:
    Description: 'Sample requests from whitelisted IPs for viewing them in WAF console'
    Type: 'AWS::SSM::Parameter::Value<String>'

Conditions:
  NumberOfSubnets1:
      !Equals [ 1, !Ref NumberOfSubnets ]
  NumberOfSubnets2:
      !Equals [ 2, !Ref NumberOfSubnets ]
  NumberOfSubnets3:
      !Equals [ 3, !Ref NumberOfSubnets ]
  NumberOfSubnets4:
      !Equals [ 4, !Ref NumberOfSubnets ]
  NumberOfSubnets5:
      !Equals [ 5, !Ref NumberOfSubnets ]
  NumberOfSubnets6:
      !Equals [ 6, !Ref NumberOfSubnets ]
  CreateAlternateDomainRecord: !Not [!Equals [!Ref HostedZoneIdAlternate, ""]]
  ELBLogging: !Equals [!Ref LogEnabled, "true"]

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub "arn:aws:s3:::avoindata-secrets/${EnvironmentName}/*"
              - Effect: Allow
                Action: "*"
                Resource:
                  - !Sub "arn:aws:s3:::avoindata-${EnvironmentName}-datasets"
                  - !Sub "arn:aws:s3:::avoindata-${EnvironmentName}-datasets/*"
              - Effect: Allow
                Action:
                  - ssm:DescribeAssociation
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:GetDocument
                  - ssm:GetManifest
                  - ssm:GetParameters
                  - ssm:ListAssociations
                  - ssm:ListInstanceAssociations
                  - ssm:PutInventory
                  - ssm:PutComplianceItems
                  - ssm:PutConfigurePackageResult
                  - ssm:UpdateAssociationStatus
                  - ssm:UpdateInstanceAssociationStatus
                  - ssm:UpdateInstanceInformation
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2messages:AcknowledgeMessage
                  - ec2messages:DeleteMessage
                  - ec2messages:FailMessage
                  - ec2messages:GetEndpoint
                  - ec2messages:GetMessages
                  - ec2messages:SendReply
                Resource: "*"
              - Effect: Allow
                Action:
                  - autoscaling:Describe*
                  - autoscaling:CompleteLifecycleAction
                Resource: "*"
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeTargetHealth
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeInstanceStatus
                Resource: "*"
              - Effect: Allow
                Action:
                  - ds:CreateComputer
                  - ds:DescribeDirectories
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeTags
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:${EnvironmentName}*"
              - Effect: Allow
                Action:
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*"
              - Effect: Allow
                Action:
                  - s3:GetEncryptionConfiguration
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - arn:aws:s3:::aws-ssm-eu-west-1/*
                  - arn:aws:s3:::aws-windows-downloads-eu-west-1/*
                  - arn:aws:s3:::amazon-ssm-eu-west-1/*
                  - arn:aws:s3:::amazon-ssm-packages-eu-west-1/*
                  - arn:aws:s3:::eu-west-1-birdwatcher-prod/*
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                Resource: !Sub "arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole


  WAF:
    Type: AWS::WAFv2::WebACL
    Properties:
      Scope: REGIONAL
      Description: Default WAF rules for DVV
      DefaultAction:
        Allow: {}
      Rules:
        - Name: allow-whitelisted-ips
          Priority: 1
          Action:
            Allow: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFAllowedIPSet.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: allowed-ips
            SampledRequestsEnabled: !Ref WafAllowedIpsRequestSampling
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 5
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: True
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesAmazonIpReputationList
        - Name: rate-limit-finland
          Priority: 10
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: !Ref WafHighPriorityRateLimit
              ScopeDownStatement:
                GeoMatchStatement:
                  CountryCodes: !Ref WafHighPriorityCountryCodes
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: request-rate-limit-finland
            SampledRequestsEnabled: !Ref WafHighPriorityRequestSampling
        - Name: rate-limit-world
          Priority: 20
          Action:
            Block: {}
          Statement:
              RateBasedStatement:
                AggregateKeyType: IP
                Limit: !Ref WafRateLimit
                ScopeDownStatement:
                  NotStatement:
                    Statement:
                      GeoMatchStatement:
                        CountryCodes: !Ref WafHighPriorityCountryCodes
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: request-rate-limit-world
            SampledRequestsEnabled: !Ref WafRequestSampling
        - Name: block-banned-ips
          Priority: 30
          Action:
            Block: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WAFBannedIPSet.Arn
          VisibilityConfig:
            CloudWatchMetricsEnabled: True
            MetricName: banned-ips
            SampledRequestsEnabled: !Ref WafBannedIpsRequestSampling
        - Name: AWS-AWSManagedRulesBotControlRuleSet
          Priority: 40
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesBotControlRuleSet
              ExcludedRules:
              - Name: CategoryAdvertising
              - Name: CategoryArchiver
              - Name: CategoryContentFetcher
              - Name: CategoryHttpLibrary
              - Name: CategoryLinkChecker
              - Name: CategoryMiscellaneous
              - Name: CategoryMonitoring
              - Name: CategoryScrapingFramework
              - Name: CategorySearchEngine
              - Name: CategorySecurity
              - Name: CategorySeo
              - Name: CategorySocialMedia
              - Name: SignalAutomatedBrowser
              - Name: SignalKnownBotDataCenter
              - Name: SignalNonBrowserUserAgent
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: True
            CloudWatchMetricsEnabled: True
            MetricName: AWS-AWSManagedRulesBotControlRuleSet
      VisibilityConfig:
        CloudWatchMetricsEnabled: True
        MetricName: DVVWAF
        SampledRequestsEnabled: !Ref WafAllTrafficRequestSampling

  WAFBannedIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref BannedIPs

  WAFAllowedIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref AllowedIPs


Outputs:
  InstanceProfileArn:
    Description: Instance profile ARN
    Value: !GetAtt InstanceProfile.Arn
    Export:
      Name: !Sub avoindata-${EnvironmentName}-instanceprofile
  WafArn:
    Description: ARN of WAF
    Value: !GetAtt WAF.Arn
    Export:
      Name: !Sub avoindata-${EnvironmentName}-wafarn
