---
# tasks file for secrets

- name: Install required packages
  apt:
    name:
     - python-pip
     - python3-pip
    state: present

- name: Install required pip packages
  pip:
    name:
      - botocore
      - boto3
    state: present

- name: Ensure secrets path exists
  file:
    path: "{{ secrets_destination_path }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  when: secrets_bucket != "does_not_exist"

- name: Copy secrets from S3 bucket
  aws_s3:
    bucket: "{{ secrets_bucket }}"
    object: "{{ secrets_bucket_path }}/{{ item }}"
    dest: "{{ secrets_destination_path }}/{{ item }}"
    mode: get
  with_items: "{{ secrets_bucket_files }}"
  when: secrets_bucket != "does_not_exist"

- name: Set permissions to secrets files
  file:
    path: "{{ secrets_destination_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0400
  with_items: "{{ secrets_bucket_files }}"
  when: secrets_bucket != "does_not_exist"

- name: Include secrets from filesystem
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "{{ secrets_destination_path }}/{{ secrets_file }}"
      skip: true
  no_log: true
