<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_guide_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_guide':
      return t('
        Creates guide module
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_guide_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_guide' => array(
      'variables' => array(
        'language' => NULL,
        'guidePageTitle' => NULL,
        'guidePage' => NULL,
        'allPages' => NULL
      ),
      'template' => 'avoindata_guide_block',
    ),
  );
}