#!/bin/bash
set -e

# init ckan datastore
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE $DB_DATASTORE_USER LOGIN PASSWORD '$DB_DATASTORE_PASS';
    CREATE DATABASE $DB_DATASTORE OWNER $DB_DATASTORE_USER ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE $DB_DATASTORE TO $DB_DATASTORE_USER;
    CREATE ROLE $DB_DATASTORE_READONLY_USER LOGIN PASSWORD '$DB_DATASTORE_READONLY_PASS';
EOSQL

# init drupal
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE $DB_DRUPAL_USER LOGIN PASSWORD '$DB_DRUPAL_PASS';
    CREATE DATABASE $DB_DRUPAL OWNER $DB_DRUPAL_USER ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE $DB_DRUPAL TO $POSTGRES_USER;
EOSQL

# init datapusher job database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE $DB_DATAPUSHER_JOBS_USER LOGIN PASSWORD '$DB_DATAPUSHER_JOBS_PASS';
    CREATE DATABASE $DB_DATAPUSHER_JOBS OWNER $DB_DATAPUSHER_JOBS_USER ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE $DB_DATAPUSHER_JOBS TO $POSTGRES_USER;
EOSQL


