<?php

/**
 * @file
 * Adds avoindata header module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_header_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_header':
      return t('
        Creates header that can be exported to non-Drupal pages.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_header_theme($existing, $type, $theme, $path) {
  return [
    'avoindata_header_search_collapsible' => [
      'template' => 'avoindata_header_search_collapsible',
      'variables' => [
        'language' => NULL,
      ],
    ],
    'avoindata_header' => [
      'template' => 'avoindata_header',
      'variables' => [
        'language' => NULL,
      ],
    ],
  ];
}
