---
nginx_development_environment: true

nginx_sites:
  - template: 'nginx_site_config.j2'
    destination: 'sites-available/ytp'
    server_name: "{{ nginx_fqdn }}"
    snippet: 'ytp.conf'
    port: "{{ nginx_port }}"
    base_hostname: "{{ nginx_domain }}"
  - template: 'nginx_site_config.j2'
    destination: 'sites-available/ytp-secondary'
    server_name: "{{ nginx_secondary_fqdn }}"
    snippet: 'ytp-secondary.conf'
    base_hostname: "{{ nginx_secondary_domain }}"
    port: "{{ nginx_port }}"
  - template: 'nginx_site_config.j2'
    destination: 'sites-available/ytp_test'
    server_name: "{{ nginx_fqdn }}"
    snippet: 'ytp_test.conf'
    base_hostname: "{{ nginx_domain }}"
    port: "9000"

nginx_enabled_sites:
  - "ytp"
  - "ytp-secondary"
  - "ytp_test"

nginx_snippet_files:
  - template: 'server.config.j2'
    destination: 'ytp.conf'
    root_redirect: "{{ nginx_hostname_language }}"
    apache_port: "{{ nginx_apache_port }}"
  - template: 'server.config.j2'
    destination: 'ytp-secondary.conf'
    root_redirect: "{{ nginx_secondary_hostname_language }}"
    apache_port: "{{ nginx_apache_port }}"
  - template: 'nginx_security_headers.conf.j2'
    destination: 'nginx_security_headers.conf'
  - template: 'server.config.j2'
    destination: 'ytp_test.conf'
    root_redirect: "{{ nginx_hostname_language }}"
    apache_port: "9090"
