<?php
/**
 * @file
 * Create footer menu here, because using hook_menu() for creating link menus
 * is frowned upon.
 */

$footer_menu = array(
  'menu_name' => 'footer-links',
  'title' => t('Footer links'),
  'description' => t('Link menu for page footer section'),
);

// Don't overwrite menu, if it exists already
$menus = menu_get_menus();
if (!array_key_exists('footer-links', $menus)) {
  menu_save($footer_menu);
}
