<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_help().
 */
function avoindata_hero_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_hero':
      return t('
        Creates header that can be exported to non-Drupal pages.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_hero_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_hero' => array(
      'render element' => 'form',
      'template' => 'avoindata_hero_form',
    ),
  );
}

function avoindata_hero_datasetCount() {
  $client = \Drupal::httpClient();

  try {
    $datasetResponse = $client->request('GET', 'http://localhost:8080/data/api/3/action/package_search');
    $datasetResult = Json::decode($datasetResponse->getBody());
    $datasetCount = $datasetResult['result']['count'];
  } catch (\Exception $e) {
    $datasetCount = 0;
  }

  return [
    '#markup' => $datasetCount,
    '#cache' => ['max-age' => 0],
  ];
}

function avoindata_hero_organizationCount(){
  $client = \Drupal::httpClient();
  try {
    $organizationResponse = $client->request('GET', 'http://localhost:8080/data/api/3/action/organization_list');
    $organizationResult = Json::decode($organizationResponse->getBody());
    $organizationCount = count($organizationResult['result']);
  } catch (\Exception $e) {
    $organizationCount = 0;
  }

  return [
    '#markup' => $organizationCount,
    '#cache' => ['max-age' => 0],
  ];
}

function avoindata_hero_applicationCount(){
  $client = \Drupal::httpClient();

  try {
    $applicationResponse = $client->request('GET', 'http://localhost:8080/data/api/3/action/ckanext_showcase_list');
    $applicationResult = Json::decode($applicationResponse->getBody());
    $applicationCount = count($applicationResult['result']);
  } catch (\Exception $e) {
    $applicationCount = 0;
  }

  return [
    '#markup' => $applicationCount,
    '#cache' => ['max-age' => 0],
  ];
}
