<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_hero_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_hero':
      return t('
        Creates header that can be exported to non-Drupal pages.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_hero_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_hero' => array(
      'render element' => 'form',
      'template' => 'avoindata_hero_form',
    ),
  );
}
