<?php

/**
 * @file
 * Adds articles component.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_articles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_articles':
      return t('
        Creates articles module.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_articles_theme($existing, $type, $theme, $path) {
  return [
    'avoindata_articles' => [
      'variables' => [
        'searchterm' => NULL,
        'articles' => NULL,
        'tags' => NULL,
        'activetags' => NULL,
        'language' => NULL,
      ],
      'template' => 'avoindata_articles_block',
    ],
  ];
}
