<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_events':
      return t('
        Creates events module.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_events_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_events' => array(
      'variables' => array(
        'searchterm' => NULL,
        'sort' => NULL,
        'showpast' => NULL,
        'events' => NULL,
        'language' => NULL,
      ),
      'template' => 'avoindata_events_block',
    ),
  );
}
