#! /bin/sh

SCRIPT_DIRECTORY=`dirname $0`
CURRENT_DIRECTORY=`pwd`
export BASE_DIRECTORY="$CURRENT_DIRECTORY/$SCRIPT_DIRECTORY/.."
export CONFIG_DIRECTORY="$BASE_DIRECTORY/config"

$SCRIPT_DIRECTORY/install-ckan.sh &&
$SCRIPT_DIRECTORY/install-drupal.sh

