<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function avoindata_articles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.avoindata_articles':
      return t('
        Creates articles module.
      ');
  }
}

/**
 * Implements hook_theme().
 */
function avoindata_articles_theme($existing, $type, $theme, $path) {
  return array(
    'avoindata_articles' => array(
      'variables' => array(
        'searchterm' => NULL,
        'articles' => NULL,
        'tags' => NULL,
        'activetags' => NULL,
        'language' => NULL,
      ),
      'template' => 'avoindata_articles_block',
    ),
  );
}
