---

# This playbook installs all roles on a single server

- hosts: all
  become: true
  vars:
    ckan_solr_host: 127.0.0.1

  pre_tasks:
    - import_role:
        name: secrets
      tags: always

  roles:
    - role: common
      tags: common
    - role: postgres
      tags: postgres
    - role: solr
      tags: solr
    - role: apache
      tags: apache
    - role: ckan
      tags: ckan
    - role: datapusher
      tags: datapusher
    - role: dynatrace
      tags: dynatrace

  post_tasks:
    - import_role:
        name: cloudwatch_agent
      when: cloudwatch_agent_enabled
      tags: cloudwatch_agent_role
