---

# This playbook installs all roles on a single server

- hosts: all
  become: true

  pre_tasks:
    - name: Ensure www directory exists
      file:
        path: "/var/www"
        state: directory

    - name: Enable maintenance mode
      file:
        path: "/var/www/maintenance"
        state: touch

    - import_role:
        name: secrets
      tags: always

    - import_role:
        name: mailhog
      when: deployment_environment_id == 'vagrant'
      tags: mailhog

  roles:
    - role: common
      tags: common
    - role: dynatrace
      tags: dynatrace
    - role: postgres
      tags: postgres
    - role: opendata_frontend
      tags: opendata_frontend
    - role: apache
      tags: apache
    - role: ckan
      tags: ckan
    - role: php
      tags: php
    - role: composer
      tags: composer
    - role: nginx
      tags: nginx
    - role: drupal
      tags: drupal
    - role: datapusher
      tags: datapusher
    - role: dcatap
      tags: dcatap

  post_tasks:
    - name: Remove maintenance mode
      file:
        path: "/var/www/maintenance"
        state: absent

    - import_role:
        name: cloudwatch_agent
      when: cloudwatch_agent_enabled
      tags: cloudwatch_agent_role
