---

cloudwatch_agent_logs_config:
  - file_path: '/var/log/ckan/ckan-worker-bulk.log*'
    log_group_name: ckan-worker-bulk
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    multi_line_start_pattern: '{timestamp_format}'

  - file_path: '/var/log/ckan/ckan-worker-priority.log*'
    log_group_name: ckan-worker-priority
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    multi_line_start_pattern: '{timestamp_format}'

  - file_path: '/var/log/ckan/fetch_consumer.log*'
    log_group_name: ckan-fetch-consumer
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    multi_line_start_pattern: '{timestamp_format}'

  - file_path: '/var/log/ckan/gather_consumer.log*'
    log_group_name: ckan-gather-consumer
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    multi_line_start_pattern: '{timestamp_format}'

  - file_path: '/var/log/ckan/ckan.log.*'
    log_group_name: ckan
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'
    multi_line_start_pattern: '{timestamp_format}'

  - file_path: '/var/log/apache2/ckan_default.custom.log*'
    log_group_name: ckan-default-custom
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'

  - file_path: '/var/log/apache2/ckan_default.error.log*'
    log_group_name: ckan-default-error
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'
    multi_line_start_pattern: "(?:\\[.*\\] ){5}ERROR"

  - file_path: '/var/log/apache2/datapusher.custom.log*'
    log_group_name: datapusher-custom
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'

  - file_path: '/var/log/apache2/datapusher.error.log*'
    log_group_name: datapusher-error
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'

  - file_path: '/var/log/apache2/access.log*'
    log_group_name: apache-access
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'

  - file_path: '/var/log/apache2/error.log*'
    log_group_name: apache-error
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%Y-%m-%d %H:%M:%S'

  - file_path: /var/log/syslog
    log_group_name: syslog
    log_stream_name: '{local_hostname}'
    timestamp_format: '%b %d %H:%M:%S'

  - file_path: /var/log/auth.log
    log_group_name: auth
    log_stream_name: '{local_hostname}'
    timestamp_format: '%b %d %H:%M:%S'

  - file_path: /var/log/supervisor/supervisord.log
    log_group_name: supervisord
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y-%m-%d %H:%M:%S'

  - file_path: /var/log/php7.0-fpm.log
    log_group_name: php7-fpm
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d-%b-%Y %H:%M:%S]'

  - file_path: /var/log/nginx/access.log
    log_group_name: nginx-access
    log_stream_name: '{local_hostname}'
    timestamp_format: '[%d/%b/%Y:%H:%M:%S %z]'

  - file_path: /var/log/nginx/error.log
    log_group_name: nginx-error
    log_stream_name: '{local_hostname}'
    timestamp_format: '%Y/%m/%d %H:%M:%S %z'

cloudwatch_agent_procstat_metrics_config:
  - pattern: "ckan_default"
    measurement:
      - cpu_usage
  - pattern: "php-fpm"
    measurement:
      - cpu_usage

cloudwatch_agent_enabled: false
