---

- name: Add Drupal roles
  command: drush role-create "{{ item }}" chdir="{{ drupal_root }}"
  ignore_errors: True
  with_items:
  - "{{ drupal_editor_rolename }}"
  - "{{ drupal_ckan_admin_rolename }}"
  - "{{ drupal_publisher_rolename }}"
  tags:
  - drupal
  - roles

- name: Copy drush add-roles script
  copy: src=roles-add.drush dest="{{ scripts_path }}/roles-add.drush" owner=root group=root mode="0750"
  tags:
  - drupal
  - drupal-configuration
  - roles

- name: Copy permissions list
  template: src=drupal-roles.json.j2 dest="{{ cache_path }}/drupal-roles.json" owner=root group=root mode="0600"
  register: drush_roles
  tags:
  - drupal
  - drupal-configuration
  - roles

- name: Set role permissions
  command: "drush {{ scripts_path }}/roles-add.drush {{ cache_path }}/drupal-roles.json chdir={{ drupal_root }}"
  when: drush_roles|changed
  tags:
  - drupal
  - drupal-configuration
  - roles
